-- Shopping vendor import from the user-provided Bite of Seattle lineup.
-- Includes 82 vendors and 139 product descriptions. Truncated source text is preserved verbatim.
-- Idempotent: existing vendors keep their UUIDs and unrelated metadata.

begin;
create extension if not exists pgcrypto;
create temporary table shopping_import(name text not null,menu_items text[] not null,sort_order integer not null) on commit drop;
insert into shopping_import(name,menu_items,sort_order) values
  ('Aihtnycity collection', array['African Clothing', 'African Jewelry', 'Glass Beads']::text[], 1000),
  ('Amusy', array['Japanese Claw Machines']::text[], 1001),
  ('Anibolic Apparel', array['Anime Merchandise']::text[], 1002),
  ('AnnGoo Nails', array['Presss-On Nails']::text[], 1003),
  ('AsianBobaGirl', array['Food Inspired Candles', 'Food Inspired Pillows', 'Boba Scented Candles']::text[], 1004),
  ('BARKS & CRAFTS', array['Pet Accessories']::text[], 1005),
  ('Bart Bridge', array['City Hats']::text[], 1006),
  ('Beyond Collectibles', array['Funko Pop Collectibles']::text[], 1007),
  ('Bubblehead Caricatures', array['Live Carricatures Drawing']::text[], 1008),
  ('CandyWrap Island', array['Decoden', 'Crochet', 'Squishies']::text[], 1009),
  ('Charm Square Inc.', array['Collectible Shoe Charms']::text[], 1010),
  ('Classy Chassis & Co.', array['Cosmetics', 'Skin Care', 'Leaf Hats']::text[], 1011),
  ('Cloris Creates', array['Unique Pet Breed''s KeychainCusto...']::text[], 1012),
  ('CNP Skulls', array['Custom Crystal Skulls']::text[], 1013),
  ('Customs by Jazz', array['DIY T-Shirt Bar']::text[], 1014),
  ('DBC Customs LLC', array['Custom Vintage Tee Apparel']::text[], 1015),
  ('Dos Casas Thrift', array['Vintage Clothing', 'Curated Accessories', 'Home Décor & Collectibles']::text[], 1016),
  ('Eat Your Soup', array['Custom Apparels']::text[], 1017),
  ('Egg Atelier', array['Handmade Crochet']::text[], 1018),
  ('Eternal Wildflowers', array['Real Botanical Jewelry', 'Mushroom Jewelry', 'Glassware Art']::text[], 1019),
  ('Fireflyslime', array['Handcrafted Scented Slime', 'Fidget Toys', 'Stress Squishies']::text[], 1020),
  ('Flawlessly fused', array['Permanent Jewelry', 'Jewelry']::text[], 1021),
  ('Fleur Viviente', array['Jewlery', 'Hair Accessories']::text[], 1022),
  ('FUTURE BLOOM', array['Premium Apparel', 'Straw Hats', 'Caps']::text[], 1023),
  ('Gallery Panda', array['Acrylic Wall Art']::text[], 1024),
  ('Glimmish', array['Hair Pins']::text[], 1025),
  ('Golden Luxe Jewels', array['Permanent Jewelries', 'Engravings']::text[], 1026),
  ('Goozee Pins', array['Poke-Avatar enamel Pins', 'Anime Vinyl Stickers', 'Anime Enamel Pins']::text[], 1027),
  ('Grace in bloom', array['Preserved Flower Resin Art']::text[], 1028),
  ('Handmade Botanic Lab', array['Handmade Flower Crochet']::text[], 1029),
  ('Henna by Mayra', array['Henna Body Art']::text[], 1030),
  ('Hollywood Light Up Gear', array['Custom Poncho']::text[], 1031),
  ('I Have Good Energy', array['Perfume Oils', 'Linen Sprays', 'Apparel']::text[], 1032),
  ('INDOCRAFT', array['Hawaiian Clothings', 'Wooden Beach Signs']::text[], 1033),
  ('Ingkarat Apparel', array['Thai Inspired Apparels', 'Harem Pants']::text[], 1034),
  ('Jale', array['Women''s Dress | Apparels']::text[], 1035),
  ('JCMstore', array['Balloons', 'Trading Cards', 'Graduation Leis']::text[], 1036),
  ('King and Queen Things', array['Pop Culture Shoe Charms']::text[], 1037),
  ('Kitty Korner', array['Collectible Shoe Charms']::text[], 1038),
  ('KRAFTTEE', array['Hand-Made Crochet Dolls']::text[], 1039),
  ('Kwanjai California', array['Crochet Flowers', 'Crochet Bags', 'Crochet Keychains']::text[], 1040),
  ('LIDA ART', array['Handmade Baskets']::text[], 1041),
  ('Lola Inspired Creations', array['Food Inspired Candles']::text[], 1042),
  ('Love Me Waist Beads', array['Waist Beads']::text[], 1043),
  ('Lumini Jewelry', array['Hypoallergenic Jewelries']::text[], 1044),
  ('Made Design Jewelry', array['Jewelries']::text[], 1045),
  ('Magnolia Lane Store', array['Candles', 'Baby Clothing', 'Accessories']::text[], 1046),
  ('Mistura Woodcoholics', array['Wooden Watches and Accessories']::text[], 1047),
  ('MIU CANDLES', array['Candles & Wax Melts', 'Aromatic Products']::text[], 1048),
  ('MrSmellgoodTX', array['Perfume | Cologne']::text[], 1049),
  ('Mystic Butterflies', array['Framed Butterflies & Insects']::text[], 1050),
  ('Nailed It Day Studios', array['Authentic Japanese Plush | Licen...']::text[], 1051),
  ('New London Enterprises', array['3D Printed Figures']::text[], 1052),
  ('Otaku Sugoi', array['Anime Themed Apparels', 'Trading Card Game']::text[], 1053),
  ('Pacific Paradise Prints', array['Keyboard Fidgets', 'Fidget Keychains']::text[], 1054),
  ('Party Animal', array['Anime-Inspired Accessories']::text[], 1055),
  ('Patchy Patchenstein', array['Iron-On Custom Patches']::text[], 1056),
  ('PATTRASHOME', array['Handmade Yarn Accessory']::text[], 1057),
  ('Quite Bloom Studio', array['Ceramics', 'Decor']::text[], 1058),
  ('Richard Jahn Art Gallery', array['Art Prints', 'Paintings']::text[], 1059),
  ('Rickymakes', array['Custom Planters', 'Custom Terrariums', 'Plants']::text[], 1060),
  ('Sacred Love LA', array['Custom Waistbeads']::text[], 1061),
  ('San Diego Crystals & Jewelry', array['Upscale Jewelries']::text[], 1062),
  ('Semper.Right.Designs', array['Custom Metal RFID Wallets']::text[], 1063),
  ('Sharp Henna', array['Henna']::text[], 1064),
  ('SmallRiniLady', array['Food Magnets', 'Kokeshi Keyrings', 'Enamel Pins']::text[], 1065),
  ('Snickerdoodles Caricatures', array['Caricatures']::text[], 1066),
  ('Snooker', array['Custom Anime Shirts', 'Custom Embroidery Sweatshirts', 'Custom Embroidery Hoodies']::text[], 1067),
  ('Soupermandoo', array['Art', 'Stickers', 'Pins']::text[], 1068),
  ('Sumac El Sol Handcrafted Textile Arts', array['Handcrafted Textile Arts', 'Sweaters', 'Blankets & Hoodies']::text[], 1069),
  ('Tee No Evil', array['Horror Themed Apparels']::text[], 1070),
  ('The DLT Jewel Co.', array['Jewelry']::text[], 1071),
  ('The Exaggerated View Caricature Company', array['Caricature']::text[], 1072),
  ('The Lucky Cuy', array['Real Alpaca Fleece Plushies']::text[], 1073),
  ('Timestamp Portraits & Art Prints', array['Custom Portraits', 'Art Print']::text[], 1074),
  ('Urban Jungle', array['Rare Plants', 'Planters', 'Plant Accesorries']::text[], 1075),
  ('Wook Pins', array['Pins', 'Tapestries', 'Pashminas']::text[], 1076),
  ('XALT STUDIO', array['Handmade Recycled Accessories', 'Tie-Dye Scarves', 'Bag Charms']::text[], 1077),
  ('Yajai', array['Plushies Toys']::text[], 1078),
  ('Yonkoma Strips', array['Photo Booth']::text[], 1079),
  ('Zuri Handicrafts', array['African Clothing', 'Jewelry', 'Home Decor']::text[], 1080),
  ('& Mutts Co.', array['Pet Collars', 'Pet Bandanas', 'Pet Accessories']::text[], 1081);
update public.vendors v set vendor_type='shopping',menu_items=s.menu_items,source='Bite of Seattle shopping lineup (user-provided)',is_active=true,sort_order=s.sort_order,updated_at=now() from shopping_import s where lower(trim(v.name))=lower(trim(s.name));
insert into public.vendors(id,name,vendor_type,cuisines,food_types,menu_items,dietary_tags,description,review_count,review_snippets,line_status,instagram_url,source,is_active,sort_order,created_at,updated_at) select gen_random_uuid(),s.name,'shopping','{}','{}',s.menu_items,'{}',null,0,'{}',null,null,'Bite of Seattle shopping lineup (user-provided)',true,s.sort_order,now(),now() from shopping_import s where not exists(select 1 from public.vendors v where lower(trim(v.name))=lower(trim(s.name)));
commit;
select count(*) shopping_vendor_count from public.vendors where source='Bite of Seattle shopping lineup (user-provided)';

