-- Bite of Seattle lineup import from the user-provided source.
-- Includes 127 Food & Beverage vendors, 3 Games, and the 5 Shopping examples actually present.
-- Idempotent: existing vendors are matched by case-insensitive trimmed name and keep their UUIDs.

begin;
create extension if not exists pgcrypto;
create temporary table lineup_import(name text not null,vendor_type text not null,menu_items text[] not null,sort_order integer not null) on commit drop;
insert into lineup_import(name,vendor_type,menu_items,sort_order) values
  ('AGUAFRESCAQUEEN', 'food', array['Aguas Frescas', 'Mini Pancakes', 'Chocolate Covered Strawberries']::text[], 0),
  ('ALL DAT DUMPLING', 'food', array['Pork Char Siu Buns', 'Beef Bulgogi Dumplings', 'Spicy Wontons']::text[], 1),
  ('ALL DAT NOODLE', 'food', array['Dat ''Cumber Cup', 'House Special Noodles', 'Chili Garlic Noodles']::text[], 2),
  ('AMOUR', 'food', array['Thai Crab Fried Rice', 'Shrimp Pad Thai', 'Muscle Pancakes']::text[], 3),
  ('ANCHOVIES AND SALT', 'food', array['Wagyu Beef Skewers', 'Shrimp Skewers']::text[], 4),
  ('BACON MANIA', 'food', array['Bacon Smash Burger', 'Bacon Wrapped Wings', 'Bacon Brownie']::text[], 5),
  ('BEIGNETS & PO BOYS', 'food', array['Beignets', 'Shrimp Po Boys', 'Chicken Po Boys']::text[], 6),
  ('BIG BABY BOTTLE', 'food', array['Fresh Lemonade', 'Big Baby Bottles', 'Free Refills']::text[], 7),
  ('BIG ISLAND POKE & GRILL', 'food', array['Shoyu Poke Nachos', 'Poke Bombs', 'Spicy Ahi Tuna Poke']::text[], 8),
  ('BINGSOO', 'food', array['Mini Bingsoo', 'Pat Bingsoo']::text[], 9),
  ('BIRRIERIA MICHI', 'food', array['Birria Tacos', 'Quesabirria Tacos', 'Birria Ramen']::text[], 10),
  ('BITES AND CREAM', 'food', array['Chicken BBQ Jumbo skewers', 'Fried Pork Siomai', 'Grilled Polpo Tapas']::text[], 11),
  ('BLASIAN EATS', 'food', array['Cajun Shrimp Boil', 'Cajun Crab Boil', 'Honey Hot Shrimp']::text[], 12),
  ('BLUE MAINE LOBSTER', 'food', array['Signature Lobster Roll', 'Buffalo Chicken Grilled Cheese', 'Seafood Mac & Cheese']::text[], 13),
  ('BOBAHOLIC CAFE', 'food', array['Croffles', 'Pandayaki']::text[], 14),
  ('BONE N MARROW', 'food', array['Garlic Butter Bone Marrow', 'Truffle Green Onion Bone Marrow']::text[], 15),
  ('C BAO', 'food', array['Belgian Pomme Frites']::text[], 16),
  ('CA C''EST BON', 'food', array['Peach Cobbler', 'Loaded Mac & Cheese', 'Hot Cheeto Boudin Balls']::text[], 17),
  ('CAN CAKES', 'food', array['Cake in a Can']::text[], 18),
  ('CHEESE WHEEL PASTA', 'food', array['Garlic Lobster Pasta', 'Truffle Cream Pasta', 'Basil Pesto Pasta']::text[], 19),
  ('CHEESY BOYS', 'food', array['Mac & Cheese Balls', 'Taco Balls', 'Buffalo Chicken Balls']::text[], 20),
  ('CHIMNEY CAKES', 'food', array['Cinnamon & Sugar Chimney Cake', 'Choco Berry Cone', 'Pistachio Berry Cone']::text[], 21),
  ('CHOPCHOP', 'food', array['Vietnamese Shredded Rice Paper', 'Fish Ball Skewers', 'Stir Fried Buttery Corn']::text[], 22),
  ('COCINA CASERA SOUTH AMERICAN RESTAURANT', 'food', array['Arepa Street Food', 'Handmade Empanadas', 'Pabellón Criollo Bento Box']::text[], 23),
  ('COCO LOCO', 'food', array['Coconut Ice Cream', 'Coconut Smoothie', 'Mango Sticky Rice']::text[], 24),
  ('CREAM & SODA', 'food', array['Cream Soda', 'Dirty Soda']::text[], 25),
  ('CRUST & CRUNCH PIZZA', 'food', array['Pizza', 'Mozzarella Sticks', 'Loaded Fries']::text[], 26),
  ('CURRY LEAF', 'food', array['Palappam', 'Roasted Duck Curry', 'Payasam Pana Cotta']::text[], 27),
  ('CAPHETERIA', 'food', array['Crema Pandan Oolong Tea', 'Pandan Oolong Tea', 'Original Avocado Smoothie']::text[], 28),
  ('DEEP FRIED FANATICS', 'food', array['Deep Fried Pizza', 'Asian Flavored Funnel Cakes']::text[], 29),
  ('DELICIEUX', 'food', array['Cinnamon Sugar Crepe', 'Strawberry Jam Crepe']::text[], 30),
  ('DIJAH''S KITCHEN', 'food', array['Jollof Rice', 'Grilled Chicken', 'Beef Suya']::text[], 31),
  ('DIM SUM MASTER', 'food', array['Noodle Soup Dumplings', 'Pork & Shrimp Dumplings']::text[], 32),
  ('DRIPS CHEESECAKE', 'food', array['Chocolate Chip Cheesecake', 'Stuffed Cookie']::text[], 33),
  ('DRUNKEN DUMPLING', 'food', array['Rainbow Xiao Long Bao', 'Handmade Dumplings']::text[], 34),
  ('E-JAE PAK MOR', 'food', array['Khao Soi Chiang Mai', 'Spicy Thai Beef Noodle Soup', 'Su Kho Thai']::text[], 35),
  ('ELLIPSIS COOKIE CO', 'food', array['Browned Butter Chocolate Chip', 'Churro Snickerdoodle', 'Sin-a-Bun']::text[], 36),
  ('ETHIOPIAN BITES BY AHADU', 'food', array['Ethiopian Vegetarian Dishes', 'Freshly Baked Injera', 'Traditional Stews']::text[], 37),
  ('ETOILE FILANTE PATISSERIE', 'food', array['Macaron', 'Cake in a Can', 'Mini Cakes']::text[], 38),
  ('FALLOW GROUND', 'food', array['Matcha Einspanner', 'Sakura Matcha Latte', 'Coconut Matcha Cloud']::text[], 39),
  ('FAMOUS PUDN', 'food', array['Famous Original Banana', 'Banana Caramel Crunch', 'Strawberry Cheesecake']::text[], 40),
  ('FLAVORZ', 'food', array['Oxtail Mac & Cheese', 'Salmon Bites', 'Cajun Shrimp']::text[], 41),
  ('GEN KOREAN BBQ', 'food', array['Galbi Rice Bowls', 'Bulgogi Rice Bowls']::text[], 42),
  ('GHOSTIX', 'food', array['Zesty Fries', 'Diced Potato Corndog', 'Flamin'' Hot Cheetos Corndog']::text[], 43),
  ('GOLDEN CRISP CAKE', 'food', array['Golden Crisp Cake', 'Scallion Pork', 'Teriyaki Chicken']::text[], 44),
  ('GOOD VIBES CONCESSIONS', 'food', array['Island Grill Musubis', 'Exotic Chicken Wings', 'Rice Bowls']::text[], 45),
  ('GOURMET CHURROS', 'food', array['Italian Ice', 'Churro Sundae', 'Loaded Nachos']::text[], 46),
  ('GOURMET SOUL BBQ', 'food', array['BBQ Sandwich Meal', 'BBQ Plate']::text[], 47),
  ('GREENSTEAMER', 'food', array['Chinese Dim Sum', 'Steam Buns', 'Siu Mai']::text[], 48),
  ('GRILLED CHEESE GARDEN', 'food', array['Rainbow Grilled Cheese', 'Grilled Cheese', 'Orange Chicken Fries']::text[], 49),
  ('GROUNDS CREAM COFFEE', 'food', array['Cookie Butter Coffee', 'Cocoa Creme Coffee', 'Tiramisu Coffee']::text[], 50),
  ('HANA HOU SHAVE ICE', 'food', array['Hawaiian Shaved Ice', 'Halo-Halo']::text[], 51),
  ('HAWAIIAN HONEY CONES', 'food', array['J-Shaped Ice Cream', 'Freeze Dried Honey Cones']::text[], 52),
  ('HGG TANGHULU', 'food', array['Blueberry Tanghulu', 'Jumbo Mixed Fruits Tanghulu']::text[], 53),
  ('HOKKAIDO RAMEN SANTOUKA', 'food', array['Shoyu Ramen', 'Miso Ramen', 'Kara Miso Ramen']::text[], 54),
  ('HOLY COW', 'food', array['Galbi Jim', 'Galbi Fries', 'Tteokbokki']::text[], 55),
  ('HOUSE OF UBE', 'food', array['Ube Cheesecake Jar', 'Ube Ice Pop', 'Ube Jelly Jar']::text[], 56),
  ('HUMOS BBQ', 'food', array['Pork Belly Lollipop', 'Choripán Grilled Argentine', 'Grilled Cheese Skewer']::text[], 57),
  ('I-TIM TODD', 'food', array['Mango Island Fried Ice Cream', 'Honeycomb Lemon Fried Ice Cream']::text[], 58),
  ('INWA BURMESE CUISINE', 'food', array['Tea Leaf Salad', 'Burmese Fritters', 'Egg Rolls']::text[], 59),
  ('J AND J LOUISIANA BBQ', 'food', array['Smoked Brisket', 'Pulled Pork', 'Rib Tips']::text[], 60),
  ('J&A ELOTERIA', 'food', array['Elote', 'Kettle Corn', 'Fresh Squeezed Lemonade']::text[], 61),
  ('JAMAICAN JERK SHACK', 'food', array['Jerk Chicken', 'Oxtail', 'Jamaican Cuisine']::text[], 62),
  ('JEREMY''S CHICKEN', 'food', array['Jollof Rice', 'Sweet Potato Waffles', 'Smoked Halal Chicken']::text[], 63),
  ('KOCHI PO-CHA', 'food', array['Korean Fried Chicken', 'Bulgogi Fries', 'Corn Cheese']::text[], 64),
  ('LAMOON THAI TEA', 'food', array['Thai Crab Fried Rice', 'Shrimp Pad Thai', 'Muscle Pancakes']::text[], 65),
  ('LASCHELAGUAS', 'food', array['Smoothies', 'Birria Tacos', 'Birria Ramen']::text[], 66),
  ('LE NOMADE', 'food', array['Banh Mi', 'Che Thai', 'Mango Sago']::text[], 67),
  ('LOBSTERHAUS', 'food', array['Grilled Maine Lobster', 'Garlic Noodles']::text[], 68),
  ('LUKE''S LOBSTER', 'food', array['Lobster Roll', 'Crab Roll', 'Smoked Salmon Roll']::text[], 69),
  ('LUMPIA BUCKET', 'food', array['Lumpia Bucket', 'Filipino Spaghetti']::text[], 70),
  ('MAISON TANGHULU', 'food', array['Mini Strawberry Tanghulu', 'Assorted Tanghulu']::text[], 71),
  ('MASTER HE', 'food', array['Pan Fried Buns', 'Braised Beef Noodle Soup']::text[], 72),
  ('MEGA CHARCOAL BBQ', 'food', array['Jumbo Lamb Skewer', 'Jumbo Beef Skewer', 'Jumbo Chicken Skewer']::text[], 73),
  ('MEKENI''S KITCHEN', 'food', array['BBQ Chicken Skewer', 'BBQ Pork Belly Pinwheel', 'Chicharones con Guacamole']::text[], 74),
  ('MEXICALI CANDY LLC', 'food', array['Chamoy Candies']::text[], 75),
  ('MOLLY KITCHEN', 'food', array['Whole Grilled Squid', 'Grilled Octopus Tentacles', 'Scallop Skewers']::text[], 76),
  ('MORE PLEASE', 'food', array['Cookies', 'Cakes', 'Cinnamon Rolls']::text[], 77),
  ('MR. BULLY', 'food', array['Hoppang (Steamed Buns)', 'Taiyaki Ice Cream', 'Light Bulb Slushie']::text[], 78),
  ('MURDER HORNET HOT SAUCE', 'food', array['Hot Sauce']::text[], 79),
  ('NANA''S FOOD BITES', 'food', array['Lumpia Cheeseburger', 'Pork Bao Buns Adobo', 'Crispy Pork Lumpia']::text[], 80),
  ('NOLA OYSTERIA', 'food', array['New Orleans Style Oysters']::text[], 81),
  ('NOODLE BOYS', 'food', array['Lemongrass Lamb Chops', 'North Shore Garlic Shrimp', 'Crispy Fried Chicken']::text[], 82),
  ('OAQUI 5 PANCIT AND LUMPIA', 'food', array['Pancit', 'Pork Lumpia']::text[], 83),
  ('OH DANG', 'food', array['OG Noods', 'Tofu Noods', 'Chicken Noods']::text[], 84),
  ('ON A STICK', 'food', array['Chicken & Waffle on a Stick', 'Corndogs', 'Dessert on a Stick']::text[], 85),
  ('PAPA KITCHEN', 'food', array['Mini Banh Mi', 'Fresh Summer Rolls', 'Loaded Beef Ramen Rolls']::text[], 86),
  ('PENNY POP POPCORN', 'food', array['Sweet & Salty Kettle Corn', 'Movie Theater Butter Popcorn', 'Rainbow Confetti Popcorn']::text[], 87),
  ('PINEAPPLE BOYS', 'food', array['Hawaiian BBQ Chicken', 'Garlic Shrimp Pineapple Bowl', 'Pork Ribs Pineapple Bowl']::text[], 88),
  ('PINK MANGO', 'food', array['Mango Sticky Rice', 'Fresh Fruit Smoothies']::text[], 89),
  ('PINOY KITCHEN PANLASANG PINOY', 'food', array['Orange Chicken Bowl', 'Spicy Teriyaki Chicken Bowl', 'Lumpia Burger Bites']::text[], 90),
  ('PLATESOFSHADE', 'food', array['Chicken Wings', 'Jollof Rice', 'Egusi & Fufu']::text[], 91),
  ('POTATO HUT', 'food', array['Potato Swirl', 'Chicken Tenders']::text[], 92),
  ('PUERTO RICAN FLAVOR', 'food', array['Empanadillas', 'Jibarito Plate', 'Pinchos']::text[], 93),
  ('PUPUSERIA NATALIE', 'food', array['Pupusa Pork Mix', 'Pupusa Bean & Cheese']::text[], 94),
  ('REEM''S KITCHEN', 'food', array['Live Knafeh Dessert', 'Chicken and Lamb', 'Eggplant Fatteh']::text[], 95),
  ('ROSAS CHURROS', 'food', array['Stuffed Churros']::text[], 96),
  ('SAUTEED POTSTICKERS', 'food', array['Pan Fried Buns', 'Braised Beef Noodle Soup']::text[], 97),
  ('SEAFOOD BABEZ', 'food', array['Cajun Seafood Boil', 'Surf & Turf Taco', 'Surf & Turf Hibachi']::text[], 98),
  ('SEATTLE KIMCHI', 'food', array['Fresh Napa Cabbage Kimchi', 'Vegan Napa Cabbage Kimchi', 'Radish Kimchi']::text[], 99),
  ('SEOUL AMIGOS', 'food', array['Korean BBQ Quesadilla', 'Korean BBQ Burrito', 'Katsu Chicken Burger']::text[], 100),
  ('SHI TAKOYAKI', 'food', array['Original Octopus Takoyaki', 'Beef & Corn Takoyaki', 'Bacon & Cheese Takoyaki']::text[], 101),
  ('SMASH KINGS', 'food', array['Donut Smash Burgers', 'Fried Chicken Lollipop']::text[], 102),
  ('SMOKE AND SPOON', 'food', array['Nacho Brisket Sandwich', 'BBQ Cornbread Pancakes', 'Berry Pulled Pork Sandwich']::text[], 103),
  ('SNOWY VILLAGE', 'food', array['Mango Bingsoo', 'Strawberry Bingsoo', 'Oreo Bingsoo']::text[], 104),
  ('SOULLGOODEATS', 'food', array['Stuffed Smoked Turkey', 'Creamy Cajun Alfredo Pasta', 'Smoked Turkey Leg']::text[], 105),
  ('SPICE COFFEE- CAFE CALIENTE', 'food', array['Assorted Coffee Bags']::text[], 106),
  ('SUGARMAMA SUGARCANE', 'food', array['Calamansi Sugarcane', 'Dragonfruit Sugarcane', 'Lychee Sugarcane']::text[], 107),
  ('SUITE J CATERING', 'food', array['Grilled Inasal Skewer', 'Fili Cheesesteak', 'Tocino Banh Mi']::text[], 108),
  ('SUSHI PIZZERIA', 'food', array['Red Dragon Pizza', 'Rainbow Pizza', 'Alaskan Pizza']::text[], 109),
  ('SWEET ART COTTON CANDY', 'food', array['Unicorn Bacon', 'Animal Cotton Candy', 'Pouf Ball']::text[], 110),
  ('SWEET BALLS OF FRYER', 'food', array['Hot Cheeto Balls', 'Sweet Balls', 'Brownie Bites']::text[], 111),
  ('SWEETLIPS', 'food', array['Shaved Frozen Fruit']::text[], 112),
  ('TACOS EL YOYO', 'food', array['Authentic Tacos', 'Burrito Bowl', 'Chicken Panini Sandwich']::text[], 113),
  ('TASTY TIME CHINESE BBQ', 'food', array['Beef Skewer', 'Lamb Skewer', 'Chicken Skewer']::text[], 114),
  ('THE HWACHAE', 'food', array['Korean Fruit Punch']::text[], 115),
  ('THE TOP RESTAURANT AND LOUNGE', 'food', array['Potstickers', 'Egg Rolls', 'Salt & Pepper Chicken Wings']::text[], 116),
  ('TRUE CAJUN', 'food', array['Frog Legs', 'Gator Bites', 'Jambalaya']::text[], 117),
  ('UNCLE TETSU', 'food', array['Cookies', 'Cheesecake Tart']::text[], 118),
  ('WARTHOG BARBEQUE PIT RESTAURANT AND CATERING', 'food', array['Loaded Mac and Cheese', 'Pulled Pork Sandwiches', 'Loaded Nachos']::text[], 119),
  ('WE BEE ROLLIN', 'food', array['Hatch Mac & Cheese Sticks', 'WaffleWings']::text[], 120),
  ('WILLIE D''S', 'food', array['Giant Turkey Legs', 'Fluffy Baked Potatoes', 'Pretzel']::text[], 121),
  ('WUT-A-PICKLE', 'food', array['Wut-A-Stuffed Pickle', 'Wut-A-Roll Up']::text[], 122),
  ('YAKITORI YADO', 'food', array['Yakitori Japanese BBQ Chicken', 'Midarashi Dango', 'Matcha Latte']::text[], 123),
  ('YI FAN NOODLES', 'food', array['Chili Garlic Noodles', 'Lollipop Chicken', 'Stir Fried Dumplings']::text[], 124),
  ('36 STREETS VIETNAMESE COFFEE & TEA', 'food', array['Vietnamese Coffee', 'Salted Coffee', 'Coffee Flight']::text[], 125),
  ('5ON95', 'food', array['Loaded Cheese Fries', 'Chicken Tenders', 'Loaded Nachos']::text[], 126),
  ('AIHTNYCITY COLLECTION', 'shopping', array['African Clothing', 'Jewelry']::text[], 127),
  ('AMUSY', 'shopping', array['Japanese Claw Machines']::text[], 128),
  ('ANIBOLIC APPAREL', 'shopping', array['Anime Merchandise']::text[], 129),
  ('BARKS & CRAFTS', 'shopping', array['Pet Accessories']::text[], 130),
  ('CHARM SQUARE INC.', 'shopping', array['Collectible Shoe Charms']::text[], 131),
  ('STICK CATCHING', 'game', array['Stick Catching Game']::text[], 132),
  ('WATERBALLERZ', 'game', array['Giant Inflatable Water Ball']::text[], 133),
  ('WATERBALLERZ (BUNGEE JUMP)', 'game', array['Trampoline', 'Bungee Jumping']::text[], 134);
update public.vendors v set vendor_type=s.vendor_type,menu_items=s.menu_items,source='Bite of Seattle lineup page (user-provided)',is_active=true,sort_order=s.sort_order,updated_at=now() from lineup_import s where lower(trim(v.name))=lower(trim(s.name));
insert into public.vendors(id,name,vendor_type,cuisines,food_types,menu_items,dietary_tags,description,review_count,review_snippets,line_status,instagram_url,source,is_active,sort_order,created_at,updated_at) select gen_random_uuid(),s.name,s.vendor_type,'{}','{}',s.menu_items,'{}',null,0,'{}',null,null,'Bite of Seattle lineup page (user-provided)',true,s.sort_order,now(),now() from lineup_import s where not exists(select 1 from public.vendors v where lower(trim(v.name))=lower(trim(s.name)));
commit;
select vendor_type,count(*) vendor_count from public.vendors where source='Bite of Seattle lineup page (user-provided)' group by vendor_type order by vendor_type;
